### ISSUE TITLE
names() of non-existing links throws exception

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#17]
Hi Eugen,

the following code

```
import pni.io.nx.h5 as nexus

file1 = nexus.create_file("file1.nxs",True)
root = file1.root()
gr = root.create_group("entry")
l2 = nexus.link("file1.nxs://entry2", root ,"link2")
l1 = nexus.link("link2", root ,"link1")

print root.names()

file1.close()
```

throws exception 

```
Traceback (most recent call last):
  File "links2.py", line 9, in <module>
    print root.names()
  File "/usr/lib/python2.7/dist-packages/pni/io/nx/h5/__init__.py", line 162, in nxgroup_names
    return [x.name for x in self]
 pni.io.ObjectError: Exception: object_error


Description:
HDF5 object ID < 0, object creation failed!

Exception thrown by:
/tmp/buildd/libpniio-1.1.0/src/nx/h5/object_imp.cpp 52  pni::io::nx::h5::object_imp::object_imp(hid_t&&)
```

and it is not possible to browse the file.

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
Hi Jan,
  the issue with the names() method is that it iterates over the objects in the group and tries to request their names which is not possible if links cannot be resolved. In principle one could fix this by taking the names from the links rather than from the concrete objects. That might be a good solution. I should do this.

What do you mean you cannot browse the files?

**Comment by jkotan** [comment]
Hi Eugen,

I cannot browse the file because the node iterator 

    import pni.io.nx.h5 as nexus

    file1 = nexus.create_file("file1.nxs",True)
    root = file1.root()
    gr = root.create_group("entry")
    l2 = nexus.link("file1.nxs://entry2", root ,"link2")
    l1 = nexus.link("link2", root ,"link1")

    for nd in root:
        pass

    file1.close()

returns also exception and in order to get information about missing links one has to use other programs or libraries.

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
Hi Jan,
  instead of looping directly over the children of a group you can also use the get_links function.

```python
for nd in nexus.get_links(root):
    print(nd.name)
```

I am very well aware of the fact that this causes an additional degree of complexity as in this case the user has to distinguish between links and objects. However, I do not see a reasonable way how to make this simpler.

**Comment by jkotan** [comment]
Thanks

**Comment by eugenwintersberger** [comment]
But I guess you are right. The names() function should return the names of the links rather than those of the objects themselves. This would also solve the problem another problem in situations where the link and the target do not have the same name.

**Comment by jkotan** [comment]
it is related to the old API.
