### ISSUE TITLE
Inconsistent group names

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#5]
Hi Eugen,

It seems that name attributes of link returns inconsistent values, i.e. depending if it is external or internal link, e.g.

```
import pni.io.nx.h5 as nexus

file1 = nexus.create_file("file1.nxs",True)
root = file1.root()
gr = root.create_group("entry")
l1 = root.link("entry","link1")
l2 = root.link("file1.nxs://entry","link2")
file1.close()

file1 = nexus.open_file("file1.nxs")
root = file1.root()
g1 = root.open("link1")
g2 = root.open("link2")

# gives 'link1'
print(g1.name)
# gives 'entry'
print(g2.name)
```

Actually, I don't know what is correct but I thing it should be consistent.

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
You are right. I can confirm this behavior which is a bit strange on the first glimpse. The behavior seems to come from the depths of the HDF5 library. I need to look this up in the documentation and try to reproduce the problem in C++ and find a fix there (if this is possible at all). 

After a bit of thinking this behavior makes somehow sense: when you open the linked object you are referring to an object in a different file. As the attributes query the concrete HDF5 object you will get its properties in the external file. What is really strange is why this works differently for internal links (softlinks).

**Comment by jkotan** [comment]
Hi Eugen,

similar things happen with fields, i.e. in the above example if you replace create_group(...) by create_field(...)

Cheers,
Jan

**Comment by eugenwintersberger** [comment]
I can confirm that. The problem seems to be the same. In the case of an external link, the object in the external file is opened and thus one gets all the information about the object in the external file. 
I do not know yet how to address this problem. I guess I need to dig deeper into the HDF5 documentation. 

However, one important point: do not use the link() method of nxgroup anymore. It is removed in the most recent version of the wrapper. Use the link() function (see documentation).
